spring:
 application:
  name: cursos
 datasource:
  driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://JJCuadrado-W10\SQLEXPRESS;databaseName=cursos
  username: sa
  password: telynet
 jpa:
  show-sql: true
  hibernate:
   dialect: org.hibernate.dialect.SQLServer2012Dialect
   naming.implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
   naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
# port: 5001
# port: 5002
 port: 5003
eureka:
 client:
  serviceUrl:
   defaultZone: http://localhost:8761/eureka
 instance:
#  instance-id: 1
#  instance-id: 2
  instance-id: 3